# The URL the site will be built for
base_url = "https://Yamavu.github.io/zola-starter-gi"
title = "Zola Starter with GI"
author = "Yamavu"
# Whether to automatically compile all Sass files in the sass directory
compile_sass = true
build_search_index = true
generate_feeds = true
ignored_content = [
    "*.kra", 
    "*.*~"
]
ignored_static = []
taxonomies = [
    { name = "tags", feed = true},
]

[search]
index_format = "elasticlunr_javascript"
search_fields = ["title", "body"]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "base16-ocean-light"


[extra]
# Put all your custom variables here
