# The URL the site will be built for
base_url = "https://Yamavu.github.io/zola-starter-gi"
title = "Zola Starter with GI"
# Whether to automatically compile all Sass files in the sass directory
compile_sass = true
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]
# Put all your custom variables here
